# https://taskfile.dev

version: '3'

dotenv: ['.env'] # Ensure you have an .env file with LOCAL_OUT_PATH mapped to your mpmissions directory. See README for example

vars:
  OUT_PATH: './out'
  ARCHIVE_FILE: arma3missions

tasks:
  local:
    cmds:
      - task: altis
        vars:
          OUT_PATH: '{{$.LOCAL_OUT_PATH}}'
      - task: tanoa
        vars:
          OUT_PATH: '{{$.LOCAL_OUT_PATH}}'
      - task: takistan
        vars:
          OUT_PATH: '{{$.LOCAL_OUT_PATH}}'
      - task: sahrani
        vars:
          OUT_PATH: '{{$.LOCAL_OUT_PATH}}'
  build:
    cmds:
      - task: clean
      - task: altis
      - task: tanoa
      - task: takistan
      - task: sahrani
      - tar -czvf {{.ARCHIVE_FILE}}.tar.gz -C '{{.OUT_PATH}}' .
      - mv {{.ARCHIVE_FILE}}.tar.gz '{{.OUT_PATH}}'
  clean:
    cmds:
      - rm -rf "{{.OUT_PATH}}"
  altis:
    cmds:
      - mkdir -p "{{.OUT_PATH}}" && cp -r co10_Escape_CUP_RU_vs_BAF0.Altis/ "{{.OUT_PATH}}/"
      - cp -r common/* '{{.OUT_PATH}}/co10_Escape_CUP_RU_vs_BAF0.Altis'
  tanoa:
    cmds:
      - cp -r co10_Escape_CUP_RU_vs_BAF2.Tanoa/ "{{.OUT_PATH}}/"
      - cp -r common/* '{{.OUT_PATH}}/co10_Escape_CUP_RU_vs_BAF2.Tanoa'
  takistan:
    cmds:
      - cp -r co10_Escape_CUP_RU_vs_BAF22.Takistan/ "{{.OUT_PATH}}/"
      - cp -r common/* '{{.OUT_PATH}}/co10_Escape_CUP_RU_vs_BAF22.Takistan'
  sahrani:
    cmds:
      - cp -r co10_Escape_CUP_USMC_vs_SLA0.Sara/ "{{.OUT_PATH}}/"
      - cp -r common/* '{{.OUT_PATH}}/co10_Escape_CUP_USMC_vs_SLA0.Sara'
