# https://taskfile.dev

version: '3'

dotenv: ['.env'] # Ensure you have an .env file with LOCAL_OUT_PATH mapped to your mpmissions directory. See README for example

vars:
  OUT_PATH: './out'
  ARCHIVE_FILE: arma3missions
  MAPS: ['Altis', 'Tanoa', 'Takistan', 'Sara']
  FACTIONS: ['CUP_RU_vs_BAF', 'CUP_USMC_vs_SLA', 'CUP_RU_vs_USMC_and_RACS']

tasks:
  build:
    silent: true
    cmds:
      - task: build-maps
  build-maps:
    silent: true
    cmds:
      - task: clean
      - task: ensure-out-dir
      - for:
          matrix:
            MAP:
              ref: .MAPS
            FACTION:
              ref: .FACTIONS
        task: build-map
        vars:
          MAP: '{{.ITEM.MAP}}'
          FACTION: '{{.ITEM.FACTION}}'
          OUT_PATH: '{{$.OUT_PATH}}'
  ensure-out-dir:
    cmds:
      - mkdir -p '{{.OUT_PATH}}'
  build-map:
    silent: true
    dotenv: ['config/{{.FACTION}}.env']
    cmds:
      - echo "Building co10_Escape_{{.FACTION}}.{{.MAP}}"
      - cp -r maps/{{.MAP}}/ "{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}"
      - cp -r common/* '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}'
      - envsubst < templates/missions/{{.MAP}}.sqm > '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}/mission.sqm'
      - envsubst < templates/include/defines.hpp > '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}/include/defines.hpp'
      - cp 'factions/{{.FACTION}}/UnitClasses.sqf' '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}/Units/UnitClasses.sqf'
  local:
    cmds:
      - task: build-maps
        vars:
          OUT_PATH: '{{$.LOCAL_OUT_PATH}}'
  clean:
    cmds:
      - rm -rf "{{.OUT_PATH}}"