# https://taskfile.dev

version: '3'

dotenv: ['.env'] # Ensure you have an .env file with LOCAL_OUT_PATH mapped to your mpmissions directory. See README for example

vars:
  OUT_PATH: './out'
  ARCHIVE_FILE: arma3missions
  MAPS: ['Altis', 'Tanoa', 'Takistan', 'Sara']
  FACTIONS: ['CUP_RU_vs_BAF', 'CUP_USMC_vs_SLA', 'CUP_RU_vs_USMC_and_RACS']

tasks:
  build:
    silent: true
    cmds:
      - task: clean
        vars:
          OUT_PATH: '{{$.OUT_PATH}}'
      - task: ensure-out-dir
      - task: radio
        vars:
          OUT_PATH: '{{$.OUT_PATH}}'
      - for:
          matrix:
            MAP:
              ref: .MAPS
            FACTION:
              ref: .FACTIONS
        task: build-map
        vars:
          MAP: '{{.ITEM.MAP}}'
          FACTION: '{{.ITEM.FACTION}}'
          OUT_PATH: '{{$.OUT_PATH}}'
      - rm "{{$.OUT_PATH}}/radio_stations.txt"
  ensure-out-dir:
    silent: true
    cmds:
      - mkdir -p '{{.OUT_PATH}}'
  build-map:
    silent: true
    dotenv: ['config/{{.FACTION}}.env']
    vars:
      RADIO_STATIONS:
        sh: cat "{{.OUT_PATH}}/radio_stations.txt"
    env:
      MAP: '{{.MAP}}'
      FACTION: '{{.FACTION}}'
      RADIO_STATIONS: '{{.RADIO_STATIONS}}'
    cmds:
      - echo "Building co10_Escape_{{.FACTION}}.{{.MAP}}"
      - cp -r maps/{{.MAP}}/ "{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}"
      - cp -r common/* '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}'
      - envsubst < templates/description.ext > '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}/description.ext'
      - envsubst < templates/missions/{{.MAP}}.sqm > '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}/mission.sqm'
      - envsubst < templates/include/defines.hpp > '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}/include/defines.hpp'
      - mkdir -p '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}/Units'
      - cp -r 'factions/{{.FACTION}}/UnitClasses.sqf' '{{.OUT_PATH}}/co10_Escape_{{.FACTION}}.{{.MAP}}/Units/UnitClasses.sqf'
  local:
    cmds:
      - task: build
        vars:
          OUT_PATH: '{{$.LOCAL_OUT_PATH}}'
  clean:
    silent: true
    cmds:
      - rm -rf "{{.OUT_PATH}}"
  ci:
    silent: true
    cmds:
      - task: build
      - tar -czvf '{{.ARCHIVE_FILE}}.tar.gz' -C '{{.OUT_PATH}}' .
      - mv '{{.ARCHIVE_FILE}}.tar.gz' out/
  
  radio:
    silent: true
    vars:
      LOCAL_LIST:
        sh: echo {{$.RADIO_STATION_NAMES}}
    cmds:
    - task: ensure-out-dir
    - rm -f {{.OUT_PATH}}/radio_stations.txt
    - for: {var: LOCAL_LIST}
      task: add-radio-station
      vars:
        NAME: '{{.ITEM}}'
        OUT_PATH: '{{$.OUT_PATH}}'

  add-radio-station:
    silent: true
    internal: true
    vars:
      STATION_URL:
        sh: echo ${{.NAME}}
      STATION_FILE: "{{.OUT_PATH}}/radio_stations.txt"
    cmds:
      - echo "  class my_station_{{.NAME}} {" >> "{{.STATION_FILE}}"
      - echo "    name = \"{{.NAME}}\"" >> "{{.STATION_FILE}}"
      - echo "    url = \"{{.STATION_URL}}\"" >> "{{.STATION_FILE}}"
      - echo "  };" >> "{{.STATION_FILE}}"
